function [BW_out,properties] = filterRegions(BW_in)
%filterRegions Filter BW image using auto-generated code from imageRegionAnalyzer app.

% Auto-generated by imageRegionAnalyzer app on 15-May-2025
%---------------------------------------------------------

BW_out = BW_in;

% Get properties.
properties = regionprops(BW_out, {'Area', 'Eccentricity', 'EquivDiameter', 'EulerNumber', 'FilledArea', 'MajorAxisLength', 'MinorAxisLength', 'BoundingBox', 'Centroid'});